{% set version = "2.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggeffects
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggeffects_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggeffects/ggeffects_{{ version }}.tar.gz
  sha256: a387ff9aa3e44f813edb39933dd9545c2307258f53bf7ea86a9a3e84d7dbaac8

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-datawizard >=1.2.0
    - r-insight >=1.3.0
    - r-reformulas
  run:
    - r-base
    - r-datawizard >=1.2.0
    - r-insight >=1.3.0
    - r-reformulas

test:
  commands:
    - $R -e "library('ggeffects')"           # [not win]
    - "\"%R%\" -e \"library('ggeffects')\""  # [win]

about:
  home: https://strengejacke.github.io/ggeffects
  license: MIT
  summary: Compute marginal effects from statistical models and returns the  result as tidy data frames. These data frames are ready to use with the  'ggplot2'-package. Marginal effects can be calculated for many different  models. Interaction terms, splines and polynomial terms are also supported.  The main functions are
    ggpredict(), ggemmeans() and ggeffect(). There is a  generic plot()-method to plot the results using 'ggplot2'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
