{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggeffects
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggeffects_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggeffects/ggeffects_{{ version }}.tar.gz
  sha256: 0d0baa182609147f8d32c93d9d8d4d302ecb7ec62cf0c526f917c9303d2179ad

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-dplyr
    - r-insight
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-scales
    - r-sjlabelled >=1.0.17
    - r-sjmisc >=2.7.8
  run:
    - r-base
    - r-mass
    - r-dplyr
    - r-insight
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-scales
    - r-sjlabelled >=1.0.17
    - r-sjmisc >=2.7.8

test:
  commands:
    - $R -e "library('ggeffects')"           # [not win]
    - "\"%R%\" -e \"library('ggeffects')\""  # [win]

about:
  home: https://strengejacke.github.io/ggeffects
  license: GPL-3
  summary: Compute marginal effects from statistical models and returns the  result as tidy data
    frames. These data frames are ready to use with the  'ggplot2'-package. Marginal
    effects can be calculated for many different  models. Interaction terms, splines
    and polynomial terms are also supported.  The main functions are ggpredict(), ggemmeans()
    and ggeffect(). There is a  generic plot()-method to plot the results using 'ggplot2'.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut

# Package: ggeffects
# Type: Package
# Encoding: UTF-8
# Title: Create Tidy Data Frames of Marginal Effects for 'ggplot' from Model Outputs
# Version: 0.8.0
# Date: 2019-01-09
# Authors@R: person("Daniel", "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206"))
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Compute marginal effects from statistical models and returns the  result as tidy data frames. These data frames are ready to use with the  'ggplot2'-package. Marginal effects can be calculated for many different  models. Interaction terms, splines and polynomial terms are also supported.  The main functions are ggpredict(), ggemmeans() and ggeffect(). There is a  generic plot()-method to plot the results using 'ggplot2'.
# License: GPL-3
# Depends: R (>= 3.2), graphics, stats, utils
# Imports: crayon, dplyr, ggplot2, lme4, magrittr, MASS, prediction, purrr, rlang, scales, sjlabelled (>= 1.0.14), sjmisc (>= 2.7.6), sjstats (>= 0.17.3), tidyr
# Suggests: brms, effects (>= 4.0-0), emmeans, glmmTMB, knitr, nlme, pscl, rmarkdown, rstanarm, rstantools, sandwich, survey, survival, testthat
# URL: https://strengejacke.github.io/ggeffects
# BugReports: https://github.com/strengejacke/ggeffects/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-01-09 15:13:11 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>)
# Repository: CRAN
# Date/Publication: 2019-01-09 16:20:03 UTC
