travis:
  secure:
    BINSTAR_TOKEN: Bm5VI2Z1vokfTcLYhFsb3Xf+JC8wLfuRtYEhpt/F41dHcgh5xrUzXqB36PiuX6c5nPbGjTvysMa64o9Zqk+9gBam6Q4ucYtq+/ypZujTkkcA0CHXhqW7p52nErei0nbKA3+LFTMm5VCtYuaHhHMOjeR9qs+DRDGJ42LoFklMC+7JQ0jjg8vs0GkZVa5RgYYH07tm2BF91YenbMZZAkVZ+Dr1SoWTbsGb9bLxiuVnn01CUg7lGgNlf+nFzZ1Ozec+jLCJhemWbOhlkFA667FwfcB4vGlWKC0p2jWh13GghDHqNuOuje7PjHhmEbsychLLF/Do7Y0KePv5M3ZI46w7A9UTvK7wIrmcciQsZVTA5khrauzpSO0RWZLSS0Wfk5VRqMFSGTHLSb17EHxWGAH4X9TqXNIWWE43Y2SK4tpvjsGVBzCRcpCHS5WYE28p56bQ5GNtEC4+A9WA9CRzYROnLuZ6s0RI+Yt4/vDxHl5cGQqvyUxKljvPM2FaYu7pc9PsD+15iowpKR3iBnqVX1UpoOjE+FssWRLspiZzmfI7d/Zkg+wdxUEg5oePeJ7KTPoJoW8H1Nsi1oypiwLvyeGW4P5/plaoSD9EzoUZ7s8/GXNTqYRZXUWwcel4pWOuO6d1876CgTsgFyVjex2rMSA4hZf75QQQKYI3n59hVtYnjyk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
