travis:
  secure:
    BINSTAR_TOKEN: Dn+16lcsXcghK0M821gnbQCNSOoomfVgtucAbU4KXr3RaUdZ/50r21B3qEiO/84N6OAURLwwq/SrF84Q3+SR5WxL3kwxCUN2PX9RkKnvEwPlQzdcBxpDivedJcr4UOBJ148Q8nEji8t564k3RcQMWqgDSgWeGgmX3g9NWaIpcmFFx8lKdQ/dakvWEMrTq4WjN0weMknev6IuHrJnEminYvYUN9VyunzuD3J+lqhlqDmw9x14GKmggTseHqhjbffKio/4asyPfRUnm7rzPKhg3DAA8y8O1G4GxuLKEoXPFFwe92zgVmnNkg+oRZsb6CuN77q5+XrNpnhwRf6rdNf8rEgab1eoZ/kC5MIirk4xxhiASnhHuVE7IPlu3/2W0LHr4uko8ANyO+no9yrsRMmJ/+GAA8gHfn5dSWJ93V7wt+cDlYoDQN28VNX7AgvnOm4I6mPwty2ukp/gWPBpKeQaKKcxE4N7D+RVzwZE3/DzJF1YTBEWyk19/4cwrL39tvexWEZysGU3E+bB+6pyiASxDB3CUuF3CdWZsyRbMuK/4V+EPQMFZ8SQ7xOspYafEDXLCeu/vxtx6mUDJ7NEM/H1uQPk6eJsmRnT2I2KMkUig/juqqSnHF0Ks4DqF2m3Ee4JpWliwnbYsQ7kFyWqZGMaJj9Fpz2Rvytd/vOS1l47mG8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
